language: objective-c
osx_image: xcode8.2
cache: cocoapods
podfile: Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - WORKSPACE="XMMediator.xcworkspace"
    - IOS_FRAMEWORK_SCHEME="XMMediator"
    - IOS_SDK=iphonesimulator10.2
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6S"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="NO"

before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install

script: 
  - xctool -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -configuration Debug ONLY_ACTIVE_ARCH=NO
  - xctool -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -configuration Release ONLY_ACTIVE_ARCH=NO

notifications:
  email: false