
language: objective-c
osx_image: xcode8.2

cache: cocoapods
podfile: Podfile

before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install

script: 
- set -o pipefail
- xcodebuild test -workspace ${POD_NAME}.xcworkspace -scheme ${POD_NAME} -sdk iphonesimulator10.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

notifications:
  email: false